package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val languageCode: String,
    val languageName: String,

    // Header & Brand
    val appName: String = "CleanCity",
    val appSubtitle: String,
    val civicBadge: String,
    val wardLabel: String,
    val switchPerspective: String,
    val logout: String,

    // Roles
    val roleCitizen: String,
    val roleCollector: String,
    val roleDriver: String,
    val roleSupervisor: String,
    val roleAdmin: String,
    val roleCitizenSubtitle: String,
    val roleCollectorSubtitle: String,
    val roleDriverSubtitle: String,
    val roleSupervisorSubtitle: String,
    val roleAdminSubtitle: String,

    // Citizen Tabs
    val tabPickup: String,
    val tabReportWaste: String,
    val tab2BinGuide: String,
    val tabAiHelp: String,
    val tabBillsUpi: String,

    // Login & Signup
    val loginTab: String,
    val signupTab: String,
    val staffTab: String,
    val citizenLoginTitle: String,
    val citizenLoginSubtitle: String,
    val citizenSignupTitle: String,
    val citizenSignupSubtitle: String,
    val staffLoginTitle: String,
    val staffLoginSubtitle: String,
    val mobileNumberLabel: String,
    val mobileNumberPlaceholder: String,
    val fullNameLabel: String,
    val fullNamePlaceholder: String,
    val municipalWardLabel: String,
    val streetAddressLabel: String,
    val streetAddressPlaceholder: String,
    val propertyCategoryLabel: String,
    val preferredLanguageLabel: String,
    val sendOtp: String,
    val otpSentNotice: String,
    val enterOtpLabel: String,
    val verifyOtp: String,
    val verifyAndLogin: String,
    val registerAndContinue: String,
    val quickDemoCitizen: String,
    val employeeIdLabel: String,
    val employeeIdPlaceholder: String,
    val staffRoleLabel: String,
    val enterDashboard: String,
    val quickStaffLogin: String,
    val catResidential: String,
    val catCommercial: String,
    val catHotel: String,
    val invalidPhoneError: String,
    val invalidOtpError: String,
    val fillAllFieldsError: String,

    // Daily Pickup Screen
    val dailyPickupStatus: String,
    val truckEnRoute: String,
    val truckCollected: String,
    val notCollectedYet: String,
    val estArrival: String,
    val wetWaste: String,
    val dryWaste: String,
    val sanitaryWaste: String,
    val householdQrCode: String,
    val qrInstructions: String,
    val segregationScore: String,
    val streakDays: String,
    val monthlyFee: String,
    val payNow: String,
    val paid: String,
    val due: String,
    val announcementsTitle: String,
    val collectionHistory: String,
    val goodSegregationBadge: String,
    val mixedSegregationBadge: String,

    // Report Waste Screen
    val reportWasteTitle: String,
    val reportWasteSubtitle: String,
    val photoEvidenceTitle: String,
    val takePhoto: String,
    val uploadGallery: String,
    val changePhoto: String,
    val photoAddedBadge: String,
    val gpsLocationTitle: String,
    val detectingGps: String,
    val refreshLocation: String,
    val wasteCategoryTitle: String,
    val catOverflowingBin: String,
    val catStreetLitter: String,
    val catConstructionDebris: String,
    val catDrainClogged: String,
    val catDeadAnimal: String,
    val descriptionTitle: String,
    val descriptionPlaceholder: String,
    val submitReport: String,
    val submittingReport: String,
    val reportSubmittedSuccess: String,
    val myReportsTitle: String,
    val filterAll: String,
    val filterPending: String,
    val filterResolved: String,
    val noReports: String,
    val statusPending: String,
    val statusInProgress: String,
    val statusResolved: String,
    val markResolved: String,

    // 2-Bin Guide
    val segregationGuideTitle: String,
    val segregationGuideSubtitle: String,
    val greenBinTitle: String,
    val greenBinDesc: String,
    val blueBinTitle: String,
    val blueBinDesc: String,
    val redBagTitle: String,
    val redBagDesc: String,
    val goldenRulesTitle: String,

    // AI Assistant
    val aiAssistantTitle: String,
    val aiAssistantSubtitle: String,
    val aiInputPlaceholder: String,
    val send: String,
    val quickQuestionsTitle: String,
    val promptPickupTimes: String,
    val promptSegregation: String,
    val promptPayFee: String,
    val promptHomeCompost: String,
    val aiThinking: String,

    // Bills & Payments
    val billsTitle: String,
    val billsSubtitle: String,
    val currentOutstanding: String,
    val payMonthlyServiceFee: String,
    val paymentSuccessTitle: String,
    val upiReference: String,
    val downloadReceipt: String,
    val transactionHistory: String,
    val close: String
)

val EnglishStrings = AppStrings(
    languageCode = "EN",
    languageName = "English",
    appSubtitle = "Municipal Solid Waste Management",
    civicBadge = "CIVIC",
    wardLabel = "Ward 42 • Indiranagar",
    switchPerspective = "SWITCH USER PERSPECTIVE",
    logout = "Sign Out",

    roleCitizen = "Citizen",
    roleCollector = "Collector",
    roleDriver = "Driver",
    roleSupervisor = "Supervisor",
    roleAdmin = "Municipal Admin",
    roleCitizenSubtitle = "Household pickup, reporting, bills and assistant",
    roleCollectorSubtitle = "Daily door-to-door route and verification",
    roleDriverSubtitle = "Bulk container pickup and weighbridge log",
    roleSupervisorSubtitle = "Live crew tracking and verification",
    roleAdminSubtitle = "Service benchmarks and municipal reports",

    tabPickup = "Home",
    tabReportWaste = "Report",
    tab2BinGuide = "Guide",
    tabAiHelp = "AI Help",
    tabBillsUpi = "Bills",

    loginTab = "Log In",
    signupTab = "Sign Up",
    staffTab = "Staff",
    citizenLoginTitle = "Citizen Access",
    citizenLoginSubtitle = "Enter your registered 10-digit mobile number to access your household pickup schedule and reports.",
    citizenSignupTitle = "Citizen Registration",
    citizenSignupSubtitle = "Register your home or business for daily segregated collection and instant civic reporting.",
    staffLoginTitle = "Municipal Operations",
    staffLoginSubtitle = "Authorized portal for waste collectors, compactor drivers, field supervisors, and municipal admins.",
    mobileNumberLabel = "Mobile Number",
    mobileNumberPlaceholder = "e.g. 9876543210",
    fullNameLabel = "Full Name",
    fullNamePlaceholder = "e.g. Lakshmi Rao",
    municipalWardLabel = "Municipal Ward",
    streetAddressLabel = "Street / House Address",
    streetAddressPlaceholder = "e.g. #14, 2nd Main, Indiranagar",
    propertyCategoryLabel = "Property Category",
    preferredLanguageLabel = "Preferred Language",
    sendOtp = "Send OTP",
    otpSentNotice = "6-digit OTP sent to your phone (Demo: 123456)",
    enterOtpLabel = "Enter 6-Digit OTP",
    verifyOtp = "Verify OTP",
    verifyAndLogin = "Verify & Log In",
    registerAndContinue = "Register & Continue",
    quickDemoCitizen = "Quick Demo Citizen",
    employeeIdLabel = "Municipal Employee ID",
    employeeIdPlaceholder = "e.g. EMP-4209",
    staffRoleLabel = "Select Staff Role",
    enterDashboard = "Enter CleanCity Dashboard",
    quickStaffLogin = "Quick Staff Login",
    catResidential = "Residential Household",
    catCommercial = "Commercial Shop",
    catHotel = "Hotel / Restaurant",
    invalidPhoneError = "Please enter a valid 10-digit mobile number",
    invalidOtpError = "Please enter valid 6-digit OTP (e.g. 123456)",
    fillAllFieldsError = "Please enter your name and street address",

    dailyPickupStatus = "Today's Waste Collection Status",
    truckEnRoute = "Truck En Route",
    truckCollected = "Collected & Verified",
    notCollectedYet = "Scheduled for Today",
    estArrival = "Estimated arrival: 07:30 AM - 08:15 AM",
    wetWaste = "Wet Waste",
    dryWaste = "Dry Waste",
    sanitaryWaste = "Sanitary / Hazard",
    householdQrCode = "Household QR Code",
    qrInstructions = "Show this QR code to the door-to-door waste collector for instant scanning and verification.",
    segregationScore = "Segregation Score",
    streakDays = "Days Streak",
    monthlyFee = "Monthly User Fee",
    payNow = "Pay Now",
    paid = "PAID",
    due = "DUE",
    announcementsTitle = "Municipal Announcements",
    collectionHistory = "Recent Collection Logs",
    goodSegregationBadge = "Good Segregation",
    mixedSegregationBadge = "Mixed Waste Warning",

    reportWasteTitle = "Report Waste Issue",
    reportWasteSubtitle = "Take a photo of uncollected trash, capture your live GPS location, and submit directly to municipal sanitation supervisors.",
    photoEvidenceTitle = "Photo Evidence",
    takePhoto = "Take Photo",
    uploadGallery = "Upload Photo",
    changePhoto = "Change Photo",
    photoAddedBadge = "Photo Attached",
    gpsLocationTitle = "GPS Location",
    detectingGps = "Detecting current GPS coordinates...",
    refreshLocation = "Refresh GPS",
    wasteCategoryTitle = "Waste Category",
    catOverflowingBin = "Overflowing Bin",
    catStreetLitter = "Street Litter",
    catConstructionDebris = "Construction Debris",
    catDrainClogged = "Clogged Drain",
    catDeadAnimal = "Animal Carcass",
    descriptionTitle = "Description & Landmark",
    descriptionPlaceholder = "Describe location details, landmark, or severity of garbage pile...",
    submitReport = "Submit Waste Report",
    submittingReport = "Submitting Report...",
    reportSubmittedSuccess = "Waste report submitted successfully to Ward 42 authorities.",
    myReportsTitle = "My Reported Issues",
    filterAll = "All",
    filterPending = "Pending",
    filterResolved = "Resolved",
    noReports = "No reports found for this filter.",
    statusPending = "PENDING",
    statusInProgress = "IN PROGRESS",
    statusResolved = "RESOLVED",
    markResolved = "Mark as Resolved",

    segregationGuideTitle = "2-Bin 1-Bag Segregation Rules",
    segregationGuideSubtitle = "Follow national municipal solid waste guidelines for clean, sustainable neighborhoods.",
    greenBinTitle = "Green Bin: Wet / Organic Waste",
    greenBinDesc = "Vegetable peels, fruit rinds, leftover food, tea leaves, eggshells, garden clippings. Hand over daily.",
    blueBinTitle = "Blue Bin: Dry / Recyclable Waste",
    blueBinDesc = "Plastic containers, paper, cardboard, tetra paks, glass bottles, metal tins. Hand over clean and dry twice a week.",
    redBagTitle = "Red Bag: Sanitary & Domestic Hazardous",
    redBagDesc = "Sanitary napkins, diapers, bandages, expired medicines, paint cans, tube lights. Wrap securely in newspaper.",
    goldenRulesTitle = "Golden Rules of Segregation",

    aiAssistantTitle = "CleanCity AI Assistant",
    aiAssistantSubtitle = "Ask questions regarding collection schedules, waste segregation, fines, or municipal services.",
    aiInputPlaceholder = "Ask about waste collection, timings, segregation...",
    send = "Send",
    quickQuestionsTitle = "Quick Questions",
    promptPickupTimes = "What are the door-to-door pickup timings today?",
    promptSegregation = "How should I segregate kitchen food waste vs plastics?",
    promptPayFee = "How can I pay my monthly sanitation user fee online?",
    promptHomeCompost = "How do I start home composting for wet kitchen waste?",
    aiThinking = "CleanCity AI is thinking...",

    billsTitle = "Sanitation User Charges",
    billsSubtitle = "Monthly municipal solid waste collection charges mandated under Solid Waste Management Bylaws.",
    currentOutstanding = "Current Outstanding",
    payMonthlyServiceFee = "Pay Monthly Fee with UPI",
    paymentSuccessTitle = "Payment Successful!",
    upiReference = "UPI Reference",
    downloadReceipt = "Download Receipt",
    transactionHistory = "Past Payment Receipts",
    close = "Close"
)

val TeluguStrings = AppStrings(
    languageCode = "TE",
    languageName = "తెలుగు (Telugu)",
    appSubtitle = "పురపాలక ఘన వ్యర్థాల సమగ్ర నిర్వహణ",
    civicBadge = "పౌర సేవ",
    wardLabel = "వార్డు 42 • ఇందిరానగర్",
    switchPerspective = "యూజర్ పాత్ర మార్చండి",
    logout = "లాగౌట్",

    roleCitizen = "పౌరుడు",
    roleCollector = "చెత్త సేకరణ సిబ్బంది",
    roleDriver = "వాహన డ్రైవర్",
    roleSupervisor = "ఫీల్డ్ సూపర్‌వైజర్",
    roleAdmin = "మునిసిపల్ అడ్మిన్",
    roleCitizenSubtitle = "ఇంటింటి పికప్, వ్యర్థాల నివేదిక, బిల్లులు మరియు సహాయకుడు",
    roleCollectorSubtitle = "రోజువారీ ఇంటింటి మార్గం మరియు క్యూఆర్ స్కానింగ్",
    roleDriverSubtitle = "బల్క్ కంటైనర్ రవాణా మరియు వేబ్రిడ్జ్ బరువు నమోదు",
    roleSupervisorSubtitle = "ప్రత్యక్ష సిబ్బంది పర్యవేక్షణ మరియు ఫిర్యాదుల పరిష్కారం",
    roleAdminSubtitle = "నగర సేవ ప్రమాణాలు, ఫైన్లు మరియు మునిసిపల్ రిపోర్టులు",

    tabPickup = "హోమ్",
    tabReportWaste = "ఫిర్యాదు",
    tab2BinGuide = "గైడ్",
    tabAiHelp = "AI",
    tabBillsUpi = "బిల్లులు",

    loginTab = "లాగిన్",
    signupTab = "సైన్ అప్",
    staffTab = "సిబ్బంది",
    citizenLoginTitle = "పౌర లాగిన్",
    citizenLoginSubtitle = "మీ ఇంటి వ్యర్థాల సేకరణ షెడ్యూల్, నివేదికలు చూడటానికి మీ 10 అంకెల మొబైల్ సంఖ్యతో లాగిన్ అవ్వండి.",
    citizenSignupTitle = "పౌర రిజిస్ట్రేషన్",
    citizenSignupSubtitle = "రోజువారీ చెత్త సేకరణ మరియు మునిసిపల్ సేవల కోసం మీ ఇంటి లేదా దుకాణం వివరాలు నమోదు చేయండి.",
    staffLoginTitle = "మునిసిపల్ సిబ్బంది పోర్టల్",
    staffLoginSubtitle = "చెత్త సేకరణ కార్మికులు, వాహన డ్రైవర్లు, ఫీల్డ్ సూపర్‌వైజర్లు మరియు అధికారుల అధికారిక లాగిన్.",
    mobileNumberLabel = "మొబైల్ సంఖ్య",
    mobileNumberPlaceholder = "ఉదా: 9876543210",
    fullNameLabel = "పూర్తి పేరు",
    fullNamePlaceholder = "ఉదా: లక్ష్మీ రావు",
    municipalWardLabel = "మునిసిపల్ వార్డు",
    streetAddressLabel = "ఇంటి నంబర్ / వీధి చిరునామా",
    streetAddressPlaceholder = "ఉదా: ఇంటి నెం. 14, 2వ మెయిన్ రోడ్డు",
    propertyCategoryLabel = "ఆస్తి రకం",
    preferredLanguageLabel = "ప్రాధాన్య భాష",
    sendOtp = "OTP పంపండి",
    otpSentNotice = "మీ మొబైల్ కు 6 అంకెల OTP పంపబడింది (డెమో: 123456)",
    enterOtpLabel = "6 అంకెల OTP నమోదు చేయండి",
    verifyOtp = "OTP ధృవీకరించండి",
    verifyAndLogin = "ధృవీకరించి లాగిన్ చేయండి",
    registerAndContinue = "ఖాతా నమోదు చేసి కొనసాగండి",
    quickDemoCitizen = "డెమో పౌర లాగిన్",
    employeeIdLabel = "ఉద్యోగి గుర్తింపు సంఖ్య (ID)",
    employeeIdPlaceholder = "ఉదా: EMP-4209",
    staffRoleLabel = "సిబ్బంది బాధ్యత ఎంచుకోండి",
    enterDashboard = "క్లీన్‌సిటీ డ్యాష్‌బోర్డ్‌లోకి వెళ్లండి",
    quickStaffLogin = "త్వరిత సిబ్బంది లాగిన్",
    catResidential = "నివాస గృహం",
    catCommercial = "వాణిజ్య దుకాణం",
    catHotel = "హోటల్ / రెస్టారెంట్",
    invalidPhoneError = "దయచేసి సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    invalidOtpError = "దయచేసి సరైన 6 అంకెల OTP నమోదు చేయండి (ఉదా: 123456)",
    fillAllFieldsError = "దయచేసి మీ పేరు మరియు చిరునామా నమోదు చేయండి",

    dailyPickupStatus = "ఈ రోజు వ్యర్థాల సేకరణ స్థితి",
    truckEnRoute = "సేకరణ వాహనం మార్గంలో ఉంది",
    truckCollected = "సేకరించబడింది & ధృవీకరించబడింది",
    notCollectedYet = "ఈ రోజు సేకరణకు నిర్దేశించబడింది",
    estArrival = "అంచనా సమయం: ఉదయం 07:30 - 08:15",
    wetWaste = "తడి వ్యర్థాలు",
    dryWaste = "పొడి వ్యర్థాలు",
    sanitaryWaste = "శానిటరీ / ప్రమాదకర",
    householdQrCode = "ఇంటి QR కోడ్",
    qrInstructions = "తక్షణ స్కానింగ్ మరియు సేకరణ నమోదు కోసం ఈ QR కోడ్‌ను చెత్త సేకరించే సిబ్బందికి చూపించండి.",
    segregationScore = "విభజన స్కోరు",
    streakDays = "నిరంతర రోజుల రికార్డు",
    monthlyFee = "నెలవారీ పౌర రుసుము",
    payNow = "ఇప్పుడే చెల్లించండి",
    paid = "చెల్లించబడింది",
    due = "బకాయి",
    announcementsTitle = "మునిసిపల్ అధికారిక ప్రకటనలు",
    collectionHistory = "ఇటీవలి సేకరణ వివరాలు",
    goodSegregationBadge = "సరిగ్గా విభజించారు",
    mixedSegregationBadge = "కలిసిపోయిన వ్యర్థాల హెచ్చరిక",

    reportWasteTitle = "వ్యర్థాల సమస్యను నివేదించండి",
    reportWasteSubtitle = "సేకరించని చెత్త కుప్పల ఫోటో తీయండి, GPS స్థానాన్ని గుర్తించి నేరుగా శానిటేషన్ సూపర్‌వైజర్‌కు ఫిర్యాదు పంపండి.",
    photoEvidenceTitle = "ఫోటో సాక్ష్యం",
    takePhoto = "ఫోటో తీయండి",
    uploadGallery = "గ్యాలరీ నుండి అప్‌లోడ్",
    changePhoto = "ఫోటో మార్చండి",
    photoAddedBadge = "ఫోటో జతచేయబడింది",
    gpsLocationTitle = "GPS లొకేషన్",
    detectingGps = "ప్రస్తుత GPS స్థానాన్ని గుర్తిస్తోంది...",
    refreshLocation = "స్థానాన్ని రిఫ్రెష్ చేయండి",
    wasteCategoryTitle = "వ్యర్థాల వర్గం",
    catOverflowingBin = "నిండిపోయిన డస్ట్ బిన్",
    catStreetLitter = "వీధిలో పారవేసిన చెత్త",
    catConstructionDebris = "భవన నిర్మాణ వ్యర్థాలు",
    catDrainClogged = "కాలువలో పేరుకుపోయిన చెత్త",
    catDeadAnimal = "మృత జంతు కళేబరం",
    descriptionTitle = "వివరణ & సమీప ల్యాండ్‌మార్క్",
    descriptionPlaceholder = "సమీప ప్రముఖ ప్రదేశం లేదా చెత్త సమస్య తీవ్రతను వివరించండి...",
    submitReport = "నివేదికను సమర్పించండి",
    submittingReport = "సమర్పిస్తోంది...",
    reportSubmittedSuccess = "వార్డు 42 అధికారులకు మీ వ్యర్థాల నివేదిక విజయవంతంగా పంపబడింది.",
    myReportsTitle = "నా నివేదికలు & ఫిర్యాదులు",
    filterAll = "అన్నీ",
    filterPending = "పరిష్కారం కాలేదు",
    filterResolved = "పరిష్కరించబడింది",
    noReports = "ఈ విభాగంలో ఎటువంటి నివేదికలు లేవు.",
    statusPending = "పెండింగ్",
    statusInProgress = "పురోగతిలో ఉంది",
    statusResolved = "పరిష్కరించబడింది",
    markResolved = "పరిష్కరించబడినట్లు గుర్తించండి",

    segregationGuideTitle = "2-బుట్టలు 1-సంచి విభజన నియమావళి",
    segregationGuideSubtitle = "పరిశుభ్రమైన, ఆరోగ్యకరమైన నగరం కోసం జాతీయ ఘన వ్యర్థాల నిర్వహణ నిబంధనలను పాటించండి.",
    greenBinTitle = "ఆకుపచ్చ బుట్ట: తడి / సేంద్రీయ వ్యర్థాలు",
    greenBinDesc = "కూరగాయల తొక్కలు, మిగిలిన ఆహారం, పండ్ల తొక్కలు, టీ పొడి, ఆకులు, పువ్వులు. ప్రతిరోజూ అందించండి.",
    blueBinTitle = "నీలి బుట్ట: పొడి / పునర్వినియోగ వ్యర్థాలు",
    blueBinDesc = "ప్లాస్టిక్ కవర్లు, కాగితం, అట్టపెట్టెలు, గాజు సీసాలు, డబ్బాలు. శుభ్రంగా మరియు పొడిగా ఉంచి వారానికి 2 సార్లు అందించండి.",
    redBagTitle = "ఎరుపు సంచి: శానిటరీ & గృహ ప్రమాదకర వ్యర్థాలు",
    redBagDesc = "శానిటరీ ప్యాడ్లు, డైపర్లు, బ్యాండేజీలు, కాలం చెల్లిన మందులు, బ్యాటరీలు. పేపర్‌లో చుట్టి అందించండి.",
    goldenRulesTitle = "చెత్త విభజన సువర్ణ సూత్రాలు",

    aiAssistantTitle = "క్లీన్‌సిటీ AI సహాయకుడు",
    aiAssistantSubtitle = "చెత్త సేకరణ సమయాలు, విభజన పద్ధతులు, యూజర్ ఫీజు లేదా మునిసిపల్ సేవల గురించి అడగండి.",
    aiInputPlaceholder = "చెత్త సేకరణ, సమయాలు, విభజన గురించి ప్రశ్న అడగండి...",
    send = "పంపండి",
    quickQuestionsTitle = "త్వరిత ప్రశ్నలు",
    promptPickupTimes = "ఈ రోజు నా వార్డులో చెత్త సేకరణ సమయాలు ఏమిటి?",
    promptSegregation = "కిచెన్ ఆహార వ్యర్థాలు మరియు ప్లాస్టిక్‌ను ఎలా వేరు చేయాలి?",
    promptPayFee = "నెలవారీ మునిసిపల్ యూజర్ ఫీజు ఆన్‌లైన్‌లో ఎలా చెల్లించాలి?",
    promptHomeCompost = "ఇంట్లోనే తడి చెత్తతో కంపోస్ట్ ఎరువు ఎలా తయారు చేయాలి?",
    aiThinking = "క్లీన్‌సిటీ AI సమాధానం సిద్ధం చేస్తోంది...",

    billsTitle = "మునిసిపల్ శానిటేషన్ యూజర్ ఫీజు",
    billsSubtitle = "ఘన వ్యర్థాల బైలా ప్రకారం నెలవారీ ఇంటింటి వ్యర్థాల సేకరణ కోసం తప్పనిసరి చార్జీలు.",
    currentOutstanding = "చెల్లించాల్సిన ప్రస్తుత బకాయి",
    payMonthlyServiceFee = "UPI ద్వారా నెలవారీ ఫీజు చెల్లించండి",
    paymentSuccessTitle = "చెల్లింపు విజయవంతమైంది!",
    upiReference = "UPI లావాదేవీ సంఖ్య",
    downloadReceipt = "రసీదు డౌన్‌లోడ్",
    transactionHistory = "గత చెల్లింపు రసీదులు",
    close = "మూసివేయండి"
)

val HindiStrings = AppStrings(
    languageCode = "HI",
    languageName = "हिन्दी (Hindi)",
    appSubtitle = "नगरपालिका ठोस अपशिष्ट प्रबंधन",
    civicBadge = "नागरिक सेवा",
    wardLabel = "वार्ड 42 • इंदिरानगर",
    switchPerspective = "उपयोगकर्ता परिप्रेक्ष्य बदलें",
    logout = "लॉग आउट",

    roleCitizen = "नागरिक",
    roleCollector = "कचरा संग्राहक",
    roleDriver = "वाहन चालक",
    roleSupervisor = "फील्ड पर्यवेक्षक",
    roleAdmin = "नगरपालिका व्यवस्थापक",
    roleCitizenSubtitle = "घर-घर कचरा संग्रह, रिपोर्टिंग, बिल और सहायता",
    roleCollectorSubtitle = "दैनिक द्वार-से-द्वार मार्ग और क्यूआर सत्यापन",
    roleDriverSubtitle = "थोक कंटेनर परिवहन और वजन पर्ची लॉग",
    roleSupervisorSubtitle = "लाइव टीम ट्रैकिंग और शिकायतों का समाधान",
    roleAdminSubtitle = "सेवा मानक, जुर्माना और नगरपालिका रिपोर्ट",

    tabPickup = "होम",
    tabReportWaste = "शिकायत",
    tab2BinGuide = "गाइड",
    tabAiHelp = "AI",
    tabBillsUpi = "बिल",

    loginTab = "लॉग इन",
    signupTab = "साइन अप",
    staffTab = "कर्मचारी",
    citizenLoginTitle = "नागरिक लॉगिन",
    citizenLoginSubtitle = "अपने घर का कचरा संग्रह शेड्यूल और रिपोर्ट देखने के लिए 10 अंकों का मोबाइल नंबर दर्ज करें।",
    citizenSignupTitle = "नागरिक पंजीकरण",
    citizenSignupSubtitle = "दैनिक कचरा संग्रह और त्वरित नागरिक सेवाओं के लिए अपने घर या दुकान का विवरण पंजीकृत करें।",
    staffLoginTitle = "नगरपालिका कर्मचारी पोर्टल",
    staffLoginSubtitle = "सफाई मित्रों, वाहन चालकों, फील्ड सुपरवाइजरों और अधिकारियों के लिए अधिकृत पोर्टल।",
    mobileNumberLabel = "मोबाइल नंबर",
    mobileNumberPlaceholder = "उदा: 9876543210",
    fullNameLabel = "पूरा नाम",
    fullNamePlaceholder = "उदा: लक्ष्मी राव",
    municipalWardLabel = "नगरपालिका वार्ड",
    streetAddressLabel = "मकान / सड़क का पता",
    streetAddressPlaceholder = "उदा: मकान नं 14, मेन रोड, इंदिरानगर",
    propertyCategoryLabel = "संपत्ति का प्रकार",
    preferredLanguageLabel = "पसंदीदा भाषा",
    sendOtp = "OTP भेजें",
    otpSentNotice = "आपके फोन पर 6 अंकों का OTP भेजा गया है (डेमो: 123456)",
    enterOtpLabel = "6 अंकों का OTP दर्ज करें",
    verifyOtp = "OTP सत्यापित करें",
    verifyAndLogin = "सत्यापित करें और लॉग इन करें",
    registerAndContinue = "पंजीकृत करें और आगे बढ़ें",
    quickDemoCitizen = "डेमो नागरिक लॉगिन",
    employeeIdLabel = "कर्मचारी आईडी (ID)",
    employeeIdPlaceholder = "उदा: EMP-4209",
    staffRoleLabel = "कर्मचारी पद चुनें",
    enterDashboard = "CleanCity डैशबोर्ड में प्रवेश करें",
    quickStaffLogin = "त्वरित कर्मचारी लॉगिन",
    catResidential = "आवासीय घर",
    catCommercial = "व्यावसायिक दुकान",
    catHotel = "होटल / रेस्तरां",
    invalidPhoneError = "कृपया मान्य 10 अंकों का मोबाइल नंबर दर्ज करें",
    invalidOtpError = "कृपया मान्य 6 अंकों का OTP दर्ज करें (उदा: 123456)",
    fillAllFieldsError = "कृपया अपना नाम और पता दर्ज करें",

    dailyPickupStatus = "आज का कचरा संग्रह स्टेटस",
    truckEnRoute = "कचरा गाड़ी रास्ते में है",
    truckCollected = "संग्रहित और सत्यापित",
    notCollectedYet = "आज संग्रह के लिए निर्धारित",
    estArrival = "अनुमानित समय: सुबह 07:30 - 08:15",
    wetWaste = "गीला कचरा",
    dryWaste = "सूखा कचरा",
    sanitaryWaste = "स्वच्छता / खतरनाक",
    householdQrCode = "घरेलू क्यूआर कोड",
    qrInstructions = "त्वरित स्कैनिंग और सत्यापन के लिए यह क्यूआर कोड कचरा संग्रह मित्र को दिखाएं।",
    segregationScore = "कचरा पृथक्करण स्कोर",
    streakDays = "लगातार दिनों का स्ट्रीक",
    monthlyFee = "मासिक उपयोगकर्ता शुल्क",
    payNow = "अभी भुगतान करें",
    paid = "भुगतान किया गया",
    due = "बाकी",
    announcementsTitle = "नगरपालिका घोषणाएं",
    collectionHistory = "हालिया कचरा संग्रह इतिहास",
    goodSegregationBadge = "उत्कृष्ट पृथक्करण",
    mixedSegregationBadge = "मिश्रित कचरा चेतावनी",

    reportWasteTitle = "कचरा समस्या की रिपोर्ट करें",
    reportWasteSubtitle = "बिना उठे कचरे की फोटो लें, अपना जीपीएस स्थान कैप्चर करें और सीधे स्वच्छता पर्यवेक्षक को भेजें।",
    photoEvidenceTitle = "फोटो प्रमाण",
    takePhoto = "फोटो लें",
    uploadGallery = "गैलरी से अपलोड करें",
    changePhoto = "फोटो बदलें",
    photoAddedBadge = "फोटो संलग्न",
    gpsLocationTitle = "GPS स्थान",
    detectingGps = "वर्तमान जीपीएस स्थान खोज रहा है...",
    refreshLocation = "स्थान रिफ्रेश करें",
    wasteCategoryTitle = "कचरा श्रेणी",
    catOverflowingBin = "भरा हुआ कचरा पात्र",
    catStreetLitter = "सड़क पर कचरा",
    catConstructionDebris = "मलबा / निर्माण कचरा",
    catDrainClogged = "नाली में कचरा",
    catDeadAnimal = "मृत पशु",
    descriptionTitle = "विवरण और लैंडमार्क",
    descriptionPlaceholder = "समीप का प्रमुख लैंडमार्क या कचरे की स्थिति का विवरण दें...",
    submitReport = "रिपोर्ट सबमिट करें",
    submittingReport = "सबमिट हो रहा है...",
    reportSubmittedSuccess = "वार्ड 42 अधिकारियों को आपकी कचरा रिपोर्ट सफलतापूर्वक भेजी गई।",
    myReportsTitle = "मेरी रिपोर्ट और शिकायतें",
    filterAll = "सभी",
    filterPending = "लंबित",
    filterResolved = "हल किया गया",
    noReports = "इस फ़िल्टर के लिए कोई रिपोर्ट नहीं मिली।",
    statusPending = "लंबित",
    statusInProgress = "प्रक्रिया में",
    statusResolved = "हल किया गया",
    markResolved = "हल के रूप में चिह्नित करें",

    segregationGuideTitle = "2-बिन 1-बैग पृथक्करण नियम",
    segregationGuideSubtitle = "स्वच्छ, स्वस्थ शहर के लिए राष्ट्रीय ठोस अपशिष्ट प्रबंधन दिशानिर्देशों का पालन करें।",
    greenBinTitle = "हरा बिन: गीला / जैविक कचरा",
    greenBinDesc = "सब्जियों और फलों के छिलके, बचा हुआ खाना, चाय पत्ती, अंडे के छिलके, पत्ते। रोजाना दें।",
    blueBinTitle = "नीला बिन: सूखा / पुनर्चक्रण योग्य कचरा",
    blueBinDesc = "प्लास्टिक की बोतलें, डिब्बे, कागज, कार्डबोर्ड, कांच की बोतलें। सूखा और साफ करके हफ्ते में 2 बार दें।",
    redBagTitle = "लाल बैग: स्वच्छता और घरेलू खतरनाक कचरा",
    redBagDesc = "सैनिटरी पैड, डायपर, पट्टियां, एक्सपायर दवाएं, पेंट, बैटरी। अखबार में लपेटकर दें।",
    goldenRulesTitle = "कचरा पृथक्करण के नियम",

    aiAssistantTitle = "CleanCity AI सहायक",
    aiAssistantSubtitle = "कचरा संग्रह समय, पृथक्करण नियमों, जुर्माने या नगरपालिका सेवाओं के बारे में प्रश्न पूछें।",
    aiInputPlaceholder = "कचरा संग्रह, समय या नियमों के बारे में पूछें...",
    send = "भेजें",
    quickQuestionsTitle = "त्वरित प्रश्न",
    promptPickupTimes = "आज मेरे क्षेत्र में कचरा गाड़ी किस समय आएगी?",
    promptSegregation = "किचन के गीले कचरे और प्लास्टिक को कैसे अलग करें?",
    promptPayFee = "मासिक उपयोगकर्ता शुल्क ऑनलाइन कैसे भरें?",
    promptHomeCompost = "घर पर ही गीले कचरे से जैविक खाद कैसे बनाएं?",
    aiThinking = "CleanCity AI उत्तर तैयार कर रहा है...",

    billsTitle = "सफाई उपयोगकर्ता शुल्क",
    billsSubtitle = "ठोस अपशिष्ट उपनियमों के तहत मासिक अनिवार्य कचरा संग्रह शुल्क।",
    currentOutstanding = "कुल बकाया राशि",
    payMonthlyServiceFee = "UPI से मासिक शुल्क का भुगतान करें",
    paymentSuccessTitle = "भुगतान सफल रहा!",
    upiReference = "UPI संदर्भ संख्या",
    downloadReceipt = "रसीद डाउनलोड करें",
    transactionHistory = "पिछली भुगतान रसीदें",
    close = "बंद करें"
)

val KannadaStrings = AppStrings(
    languageCode = "KN",
    languageName = "ಕನ್ನಡ (Kannada)",
    appSubtitle = "ಪಾಲಿಕೆ ಘನತ್ಯಾಜ್ಯ ಸಮಗ್ರ ನಿರ್ವಹಣೆ",
    civicBadge = "ನಾಗರಿಕ ಸೇವೆ",
    wardLabel = "ವಾರ್ಡ್ 42 • ಇಂದಿರಾನಗರ",
    switchPerspective = "ಬಳಕೆದಾರ ಪಾತ್ರ ಬದಲಿಸಿ",
    logout = "ಲಾಗ್ ಔಟ್",

    roleCitizen = "ನಾಗರಿಕ",
    roleCollector = "ತ್ಯಾಜ್ಯ ಸಂಗ್ರಾಹಕ",
    roleDriver = "ವಾಹನ ಚಾಲಕ",
    roleSupervisor = "ಕ್ಷೇತ್ರ ಮೇಲ್ವಿಚಾರಕ",
    roleAdmin = "ಪಾಲಿಕೆ ಆಡಳಿತಾಧಿಕಾರಿ",
    roleCitizenSubtitle = "ಮನೆ ಮನೆ ಕಸ ಸಂಗ್ರಹ, ವರದಿ, ಬಿಲ್ ಮತ್ತು ಸಹಾಯಕ",
    roleCollectorSubtitle = "ದೈನಂದಿನ ಮನೆ ಮನೆ ಮಾರ್ಗ ಮತ್ತು ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್",
    roleDriverSubtitle = "ಬೃಹತ್ ತ್ಯಾಜ್ಯ ಸಾಗಣೆ ಮತ್ತು ತೂಕ ದಾಖಲೆ",
    roleSupervisorSubtitle = "ಸಿಬ್ಬಂದಿ ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ದೂರು ಪರಿಹಾರ",
    roleAdminSubtitle = "ಸೇವಾ ಮಾನದಂಡಗಳು, ದಂಡ ಮತ್ತು ಪಾಲಿಕೆ ವರದಿಗಳು",

    tabPickup = "ಮುಖಪುಟ",
    tabReportWaste = "ದೂರು",
    tab2BinGuide = "ಮಾರ್ಗದರ್ಶಿ",
    tabAiHelp = "AI",
    tabBillsUpi = "ಬಿಲ್ಲುಗಳು",

    loginTab = "ಲಾಗ್ ಇನ್",
    signupTab = "ಸೈನ್ ಅಪ್",
    staffTab = "ಸಿಬ್ಬಂದಿ",
    citizenLoginTitle = "ನಾಗರಿಕ ಲಾಗಿನ್",
    citizenLoginSubtitle = "ನಿಮ್ಮ ಮನೆ ಕಸ ಸಂಗ್ರಹ ವೇಳಾಪಟ್ಟಿ ಮತ್ತು ವರದಿಗಳನ್ನು ನೋಡಲು 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.",
    citizenSignupTitle = "ನಾಗರಿಕ ನೋಂದಣಿ",
    citizenSignupSubtitle = "ದೈನಂದಿನ ಕಸ ಸಂಗ್ರಹಣೆಗಾಗಿ ನಿಮ್ಮ ಮನೆ ಅಥವಾ ಅಂಗಡಿಯ ವಿವರಗಳನ್ನು ನೋಂದಾಯಿಸಿ.",
    staffLoginTitle = "ಪಾಲಿಕೆ ಸಿಬ್ಬಂದಿ ಪೋರ್ಟಲ್",
    staffLoginSubtitle = "ಕಸ ಸಂಗ್ರಹ ಕಾರ್ಮಿಕರು, ಚಾಲಕರು ಮತ್ತು ಅಧಿಕಾರಿಗಳ ಅಧಿಕೃತ ಲಾಗಿನ್.",
    mobileNumberLabel = "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    mobileNumberPlaceholder = "ಉದಾ: 9876543210",
    fullNameLabel = "ಪೂರ್ಣ ಹೆಸರು",
    fullNamePlaceholder = "ಉದಾ: ಲಕ್ಷ್ಮಿ ರಾವ್",
    municipalWardLabel = "ಪಾಲಿಕೆ ವಾರ್ಡ್",
    streetAddressLabel = "ಮನೆ / ರಸ್ತೆ ವಿಳಾಸ",
    streetAddressPlaceholder = "ಉದಾ: ಮನೆ ನಂ. 14, ಮುಖ್ಯ ರಸ್ತೆ, ಇಂದಿರಾನಗರ",
    propertyCategoryLabel = "ಆಸ್ತಿ ಪ್ರಕಾರ",
    preferredLanguageLabel = "ಆದ್ಯತೆಯ ಭಾಷೆ",
    sendOtp = "OTP ಕಳುಹಿಸಿ",
    otpSentNotice = "ನಿಮ್ಮ ಮೊಬೈಲ್‌ಗೆ 6 ಅಂಕಿಯ OTP ಕಳುಹಿಸಲಾಗಿದೆ (ಡೆಮೊ: 123456)",
    enterOtpLabel = "6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ",
    verifyOtp = "OTP ಪರಿಶೀಲಿಸಿ",
    verifyAndLogin = "ಪರಿಶೀಲಿಸಿ ಲಾಗ್ ಇನ್ ಮಾಡಿ",
    registerAndContinue = "ನೋಂದಾಯಿಸಿ ಮುಂದುವರಿಯಿರಿ",
    quickDemoCitizen = "ಡೆಮೊ ನಾಗರಿಕ ಲಾಗಿನ್",
    employeeIdLabel = "ಉದ್ಯೋಗಿ ಗುರುತಿನ ಸಂಖ್ಯೆ (ID)",
    employeeIdPlaceholder = "ಉದಾ: EMP-4209",
    staffRoleLabel = "ಸಿಬ್ಬಂದಿ ಪಾತ್ರ ಆಯ್ಕೆಮಾಡಿ",
    enterDashboard = "CleanCity ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ",
    quickStaffLogin = "ತ್ವರಿತ ಸಿಬ್ಬಂದಿ ಲಾಗಿನ್",
    catResidential = "ವಸತಿ ಮನೆ",
    catCommercial = "ವಾಣಿಜ್ಯ ಮಳಿಗೆ",
    catHotel = "ಹೋಟೆಲ್ / ರೆಸ್ಟೋರೆಂಟ್",
    invalidPhoneError = "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    invalidOtpError = "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ",
    fillAllFieldsError = "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",

    dailyPickupStatus = "ಇಂದಿನ ಕಸ ಸಂಗ್ರಹಣೆ ಸ್ಥಿತಿ",
    truckEnRoute = "ಕಸದ ವಾಹನ ದಾರಿಯಲ್ಲಿದೆ",
    truckCollected = "ಸಂಗ್ರಹಿಸಿ ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    notCollectedYet = "ಇಂದಿನ ಸಂಗ್ರಹಣೆಗೆ ನಿಗದಿಯಾಗಿದೆ",
    estArrival = "ಅಂದಾಜು ಸಮಯ: ಬೆಳಿಗ್ಗೆ 07:30 - 08:15",
    wetWaste = "ಹಸಿ ತ್ಯಾಜ್ಯ",
    dryWaste = "ಒಣ ತ್ಯಾಜ್ಯ",
    sanitaryWaste = "ಸ್ಯಾನಿಟರಿ / ಅಪಾಯಕಾರಿ",
    householdQrCode = "ಮನೆಯ ಕ್ಯೂಆರ್ ಕೋಡ್",
    qrInstructions = "ತಕ್ಷಣದ ಸ್ಕ್ಯಾನಿಂಗ್‌ಗಾಗಿ ಈ ಕ್ಯೂಆರ್ ಕೋಡ್ ಅನ್ನು ಕಸ ಸಂಗ್ರಹ ಸಿಬ್ಬಂದಿಗೆ ತೋರಿಸಿ.",
    segregationScore = "ವಿಂಗಡಣೆ ಅಂಕಗಳು",
    streakDays = "ದಿನಗಳ ಸತತ ದಾಖಲೆ",
    monthlyFee = "ಮಾಸಿಕ ಶುಲ್ಕ",
    payNow = "ಈಗ ಪಾವತಿಸಿ",
    paid = "ಪಾವತಿಸಲಾಗಿದೆ",
    due = "ಬಾಕಿ ಇದೆ",
    announcementsTitle = "ಪಾಲಿಕೆ ಅಧಿಕೃತ ಪ್ರಕಟಣೆಗಳು",
    collectionHistory = "ಇತ್ತೀಚಿನ ಸಂಗ್ರಹ ಲಾಗ್‌ಗಳು",
    goodSegregationBadge = "ಉತ್ತಮ ವಿಂಗಡಣೆ",
    mixedSegregationBadge = "ಮಿಶ್ರ ಕಸ ಎಚ್ಚರಿಕೆ",

    reportWasteTitle = "ತ್ಯಾಜ್ಯ ಸಮಸ್ಯೆಯ ವರದಿ",
    reportWasteSubtitle = "ಎಸೆಯಲಾದ ಕಸದ ಫೋಟೋ ತೆಗೆಯಿರಿ, ಜಿಪಿಎಸ್ ಸ್ಥಳ ಗುರುತಿಸಿ ನೇರವಾಗಿ ಪಾಲಿಕೆಗೆ ದೂರು ಸಲ್ಲಿಸಿ.",
    photoEvidenceTitle = "ಫೋಟೋ ಸಾಕ್ಷ್ಯ",
    takePhoto = "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    uploadGallery = "ಗ್ಯಾಲರಿಯಿಂದ ಅಪ್‌ಲೋಡ್",
    changePhoto = "ಫೋಟೋ ಬದಲಾಯಿಸಿ",
    photoAddedBadge = "ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಿದೆ",
    gpsLocationTitle = "GPS ಸ್ಥಳ",
    detectingGps = "ಪ್ರಸ್ತುತ ಸ್ಥಳ ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...",
    refreshLocation = "ಸ್ಥಳ ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    wasteCategoryTitle = "ತ್ಯಾಜ್ಯ ವರ್ಗ",
    catOverflowingBin = "ತುಂಬಿ ಹರಿಯುತ್ತಿರುವ ಕಸದ ತೊಟ್ಟಿ",
    catStreetLitter = "ರಸ್ತೆಯ ಕಸ",
    catConstructionDebris = "ಕಟ್ಟಡ ತ್ಯಾಜ್ಯ / ಅವಶೇಷಗಳು",
    catDrainClogged = "ಚರಂಡಿಯಲ್ಲಿ ತುಂಬಿದ ಕಸ",
    catDeadAnimal = "ಸತ್ತ ಪ್ರಾಣಿ",
    descriptionTitle = "ವಿವರಣೆ ಮತ್ತು ಹೆಗ್ಗುರುತು",
    descriptionPlaceholder = "ಹತ್ತಿರದ ಹೆಗ್ಗುರುತು ಅಥವಾ ಕಸದ ವಿವರಗಳನ್ನು ಬರೆಯಿರಿ...",
    submitReport = "ವರದಿ ಸಲ್ಲಿಸಿ",
    submittingReport = "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    reportSubmittedSuccess = "ವಾರ್ಡ್ 42 ಅಧಿಕಾರಿಗಳಿಗೆ ನಿಮ್ಮ ತ್ಯಾಜ್ಯ ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ತಲುಪಿದೆ.",
    myReportsTitle = "ನನ್ನ ವರದಿಗಳು ಮತ್ತು ದೂರುಗಳು",
    filterAll = "ಎಲ್ಲಾ",
    filterPending = "ಬಾಕಿ ಉಳಿದಿದೆ",
    filterResolved = "ಪರಿಹರಿಸಲಾಗಿದೆ",
    noReports = "ಯಾವುದೇ ವರದಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    statusPending = "ಬಾಕಿ ಇದೆ",
    statusInProgress = "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    statusResolved = "ಪರಿಹರಿಸಲಾಗಿದೆ",
    markResolved = "ಪರಿಹರಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",

    segregationGuideTitle = "2-ಬುಟ್ಟಿ 1-ಚೀಲ ವಿಂಗಡಣೆ ನಿಯಮಗಳು",
    segregationGuideSubtitle = "ಸ್ವಚ್ಛ ನಗರಕ್ಕಾಗಿ ರಾಷ್ಟ್ರೀಯ ಘನತ್ಯಾಜ್ಯ ನಿರ್ವಹಣಾ ನಿಯಮಗಳನ್ನು ಪಾಲಿಸಿ.",
    greenBinTitle = "ಹಸಿರು ಬುಟ್ಟಿ: ಹಸಿ / ಜೈವಿಕ ತ್ಯಾಜ್ಯ",
    greenBinDesc = "ತರಕಾರಿ ಸಿಪ್ಪೆಗಳು, ಆಹಾರ, ಹಣ್ಣಿನ ತ್ಯಾಜ್ಯ, ಚಹಾ ಪುಡಿ, ಎಲೆಗಳು. ಪ್ರತಿದಿನ ನೀಡಿ.",
    blueBinTitle = "ನೀಲಿ ಬುಟ್ಟಿ: ಒಣ / ಮರುಬಳಕೆಯ ತ್ಯಾಜ್ಯ",
    blueBinDesc = "ಪ್ಲಾಸ್ಟಿಕ್, ಕಾಗದ, ಗಾಜು, ಬಾಟಲಿಗಳು, ಲೋಹ. ಒಣಗಿಸಿ ವಾರಕ್ಕೆ 2 ಬಾರಿ ನೀಡಿ.",
    redBagTitle = "ಕೆಂಪು ಚೀಲ: ಸ್ಯಾನಿಟರಿ ಮತ್ತು ಅಪಾಯಕಾರಿ ತ್ಯಾಜ್ಯ",
    redBagDesc = "ಸ್ಯಾನಿಟರಿ ಪ್ಯಾಡ್, ಡೈಪರ್, ಬ್ಯಾಂಡೇಜ್, ಹಳೆಯ ಔಷಧ, ಬ್ಯಾಟರಿಗಳು. ಪೇಪರ್‌ನಲ್ಲಿ ಸುತ್ತಿ ನೀಡಿ.",
    goldenRulesTitle = "ಕಸ ವಿಂಗಡಣೆಯ ನಿಯಮಗಳು",

    aiAssistantTitle = "CleanCity AI ಸಹಾಯಕ",
    aiAssistantSubtitle = "ಕಸ ಸಂಗ್ರಹ ಸಮಯ, ವಿಂಗಡಣೆ ನಿಯಮಗಳು, ಶುಲ್ಕ ಅಥವಾ ಪಾಲಿಕೆ ಸೇವೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ.",
    aiInputPlaceholder = "ಕಸ ಸಂಗ್ರಹಣೆ, ಸಮಯ, ವಿಂಗಡಣೆಯ ಬಗ್ಗೆ ಪ್ರಶ್ನಿಸಿ...",
    send = "ಕಳುಹಿಸಿ",
    quickQuestionsTitle = "ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು",
    promptPickupTimes = "ಇಂದು ನನ್ನ ಪ್ರದೇಶದಲ್ಲಿ ಕಸ ಸಂಗ್ರಹ ಸಮಯ ಯಾವುದು?",
    promptSegregation = "ಕಿಚನ್ ಹಸಿ ಕಸ ಮತ್ತು ಪ್ಲಾಸ್ಟಿಕ್ ಅನ್ನು ಹೇಗೆ ಬೇರ್ಪಡಿಸಬೇಕು?",
    promptPayFee = "ಮಾಸಿಕ ಪಾಲಿಕೆ ಕಸ ಸಂಗ್ರಹ ಶುಲ್ಕವನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಹೇಗೆ ಪಾವತಿಸುವುದು?",
    promptHomeCompost = "ಮನೆಯಲ್ಲೇ ಹಸಿ ಕಸದಿಂದ ಸಾವಯವ ಗೊಬ್ಬರ ತಯಾರಿಸುವುದು ಹೇಗೆ?",
    aiThinking = "CleanCity AI ಉತ್ತರಿಸುತ್ತಿದೆ...",

    billsTitle = "ಪಾಲಿಕೆ ನೈರ್ಮಲ್ಯ ಶುಲ್ಕ",
    billsSubtitle = "ಘನತ್ಯಾಜ್ಯ ಉಪನಿಯಮಗಳ ಅಡಿಯಲ್ಲಿ ಮಾಸಿಕ ಕಡ್ಡಾಯ ಶುಲ್ಕ.",
    currentOutstanding = "ಒಟ್ಟು ಬಾಕಿ ಮೊತ್ತ",
    payMonthlyServiceFee = "UPI ಮೂಲಕ ಮಾಸಿಕ ಶುಲ್ಕ ಪಾವತಿಸಿ",
    paymentSuccessTitle = "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    upiReference = "UPI ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ",
    downloadReceipt = "ರಸೀದಿ ಡೌನ್‌ಲೋಡ್",
    transactionHistory = "ಹಿಂದಿನ ಪಾವತಿ ರಸೀದಿಗಳು",
    close = "ಮುಚ್ಚಿ"
)

val TamilStrings = AppStrings(
    languageCode = "TA",
    languageName = "தமிழ் (Tamil)",
    appSubtitle = "மாநகராட்சி திடக்கழிவு மேலாண்மை",
    civicBadge = "குடிமக்கள் சேவை",
    wardLabel = "வார்டு 42 • இந்திராநகர்",
    switchPerspective = "பயனர் நிலையை மாற்றவும்",
    logout = "வெளியேறு",

    roleCitizen = "குடிமகன்",
    roleCollector = "குப்பை சேகரிப்பாளர்",
    roleDriver = "வாகன ஓட்டுநர்",
    roleSupervisor = "கள மேற்பார்வையாளர்",
    roleAdmin = "மாநகராட்சி நிர்வாகி",
    roleCitizenSubtitle = "வீட்டு குப்பை சேகரிப்பு, புகார், பில்கள் மற்றும் AI உதவி",
    roleCollectorSubtitle = "தினசரி வீடு வீடான பாதை மற்றும் க்யூஆர் சரிபார்ப்பு",
    roleDriverSubtitle = "மொத்த குப்பை போக்குவரத்து மற்றும் எடை பதிவு",
    roleSupervisorSubtitle = "நேரலை குழு கண்காணிப்பு மற்றும் தீர்வு",
    roleAdminSubtitle = "சேவை தரநிலைகள், அபராதங்கள் மற்றும் அறிக்கைகள்",

    tabPickup = "முகப்பு",
    tabReportWaste = "புகார்",
    tab2BinGuide = "வழிகாட்டி",
    tabAiHelp = "AI",
    tabBillsUpi = "கட்டணம்",

    loginTab = "உள்நுழை",
    signupTab = "பதிவு செய்",
    staffTab = "ஊழியர்",
    citizenLoginTitle = "குடிமக்கள் உள்நுழைவு",
    citizenLoginSubtitle = "உங்கள் வீட்டு குப்பை சேகரிப்பு அட்டவணை மற்றும் புகார்களைப் பார்க்க 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.",
    citizenSignupTitle = "குடிமக்கள் பதிவு",
    citizenSignupSubtitle = "தினசரி குப்பை சேகரிப்பு சேவைக்காக உங்கள் வீடு அல்லது கடையை பதிவு செய்யவும்.",
    staffLoginTitle = "மாநகராட்சி ஊழியர் தளம்",
    staffLoginSubtitle = "துப்புரவுப் பணியாளர்கள், ஓட்டுநர்கள் மற்றும் அதிகாரிகளுக்கான அங்கீகரிக்கப்பட்ட தளம்.",
    mobileNumberLabel = "மொபைல் எண்",
    mobileNumberPlaceholder = "எ.கா: 9876543210",
    fullNameLabel = "முழு பெயர்",
    fullNamePlaceholder = "எ.கா: லட்சுமி ராவ்",
    municipalWardLabel = "மாநகராட்சி வார்டு",
    streetAddressLabel = "வீட்டு எண் / தெரு முகவரி",
    streetAddressPlaceholder = "எ.கா: கதவு எண் 14, பிரதான சாலை",
    propertyCategoryLabel = "சொத்து வகை",
    preferredLanguageLabel = "விருப்ப மொழி",
    sendOtp = "OTP அனுப்பவும்",
    otpSentNotice = "உங்கள் தொலைபேசிக்கு 6 இலக்க OTP அனுப்பப்பட்டுள்ளது (டெமோ: 123456)",
    enterOtpLabel = "6 இலக்க OTP உள்ளிடவும்",
    verifyOtp = "OTP சரிபார்க்கவும்",
    verifyAndLogin = "சரிபார்த்து உள்நுழையவும்",
    registerAndContinue = "பதிவு செய்து தொடரவும்",
    quickDemoCitizen = "டெமோ குடிமகன்",
    employeeIdLabel = "ஊழியர் அடையாள எண் (ID)",
    employeeIdPlaceholder = "எ.கா: EMP-4209",
    staffRoleLabel = "ஊழியர் பொறுப்பைத் தேர்ந்தெடுக்கவும்",
    enterDashboard = "CleanCity முகப்புக்குச் செல்லவும்",
    quickStaffLogin = "விரைவு ஊழியர் உள்நுழைவு",
    catResidential = "குடியிருப்பு வீடு",
    catCommercial = "வணிகக் கடை",
    catHotel = "உணவகம் / விடுதி",
    invalidPhoneError = "சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    invalidOtpError = "சரியான 6 இலக்க OTP உள்ளிடவும்",
    fillAllFieldsError = "உங்கள் பெயர் மற்றும் முகவரியை உள்ளிடவும்",

    dailyPickupStatus = "இன்றைய குப்பை சேகரிப்பு நிலை",
    truckEnRoute = "குப்பை வாகனம் வந்துகொண்டிருக்கிறது",
    truckCollected = "சேகரிக்கப்பட்டு சரிபார்க்கப்பட்டது",
    notCollectedYet = "இன்று சேகரிக்க திட்டமிடப்பட்டுள்ளது",
    estArrival = "எதிர்பார்க்கப்படும் நேரம்: காலை 07:30 - 08:15",
    wetWaste = "ஈரக் கழிவு",
    dryWaste = "உலர் கழிவு",
    sanitaryWaste = "சுகாதார / அபாயகர கழிவு",
    householdQrCode = "வீட்டு க்யூஆர் குறியீடு",
    qrInstructions = "உடனடி சரிபார்ப்புக்கு இந்த க்யூஆர் குறியீட்டை துப்புரவுப் பணியாளரிடம் காட்டவும்.",
    segregationScore = "பிரித்தல் மதிப்பெண்",
    streakDays = "தொடர்ச்சியான நாட்கள்",
    monthlyFee = "மாதாந்திர கட்டணம்",
    payNow = "இப்போது செலுத்தவும்",
    paid = "செலுத்தப்பட்டது",
    due = "நிலுவை",
    announcementsTitle = "மாநகராட்சி அறிவிப்புகள்",
    collectionHistory = "சமீபத்திய சேகரிப்பு வரலாறு",
    goodSegregationBadge = "சிறந்த கழிவுப் பிரித்தல்",
    mixedSegregationBadge = "கலந்த குப்பை எச்சரிக்கை",

    reportWasteTitle = "குப்பை புகார் பதிவு",
    reportWasteSubtitle = "தேங்கிய குப்பையை புகைப்படம் எடுத்து, GPS இருப்பிடத்துடன் மாநகராட்சிக்கு உடனே புகார் செய்யவும்.",
    photoEvidenceTitle = "புகைப்பட ஆதாரம்",
    takePhoto = "புகைப்படம் எடுக்கவும்",
    uploadGallery = "கேலரியில் இருந்து பதிவேற்றவும்",
    changePhoto = "புகைப்படத்தை மாற்றவும்",
    photoAddedBadge = "புகைப்படம் இணைக்கப்பட்டது",
    gpsLocationTitle = "GPS இருப்பிடம்",
    detectingGps = "தற்போதைய GPS இருப்பிடத்தைக் கண்டறிகிறது...",
    refreshLocation = "இருப்பிடத்தை புதுப்பிக்கவும்",
    wasteCategoryTitle = "குப்பை வகை",
    catOverflowingBin = "நிரம்பி வழியும் குப்பைத் தொட்டி",
    catStreetLitter = "தெருவோரக் குப்பை",
    catConstructionDebris = "கட்டிடக் கழிவுகள்",
    catDrainClogged = "சாக்கடையில் அடைபட்ட குப்பை",
    catDeadAnimal = "இறந்த விலங்கு",
    descriptionTitle = "விளக்கம் மற்றும் அடையாளக்குறி",
    descriptionPlaceholder = "அருகிலுள்ள முக்கிய அடையாளக்குறி அல்லது விவரங்களை எழுதவும்...",
    submitReport = "புகாரை சமர்ப்பிக்கவும்",
    submittingReport = "சமர்ப்பிக்கப்படுகிறது...",
    reportSubmittedSuccess = "வார்டு 42 அதிகாரிகளுக்கு உங்கள் குப்பை அறிக்கை வெற்றிகரமாக அனுப்பப்பட்டது.",
    myReportsTitle = "எனது அறிக்கைகள் மற்றும் புகார்கள்",
    filterAll = "அனைத்தும்",
    filterPending = "நிலுவையில் உள்ளது",
    filterResolved = "தீர்க்கப்பட்டது",
    noReports = "எந்த புகாரும் காணப்படவில்லை.",
    statusPending = "நிலுவை",
    statusInProgress = "நடைபெறுகிறது",
    statusResolved = "தீர்க்கப்பட்டது",
    markResolved = "தீர்க்கப்பட்டதாகக் குறிக்கவும்",

    segregationGuideTitle = "2-தொட்டி 1-பை கழிவுப் பிரித்தல் விதிகள்",
    segregationGuideSubtitle = "தூய்மையான நகரத்திற்காக தேசிய திடக்கழிவு மேலாண்மை விதிகளைப் பின்பற்றவும்.",
    greenBinTitle = "பச்சைத் தொட்டி: ஈர / மக்கும் கழிவு",
    greenBinDesc = "காய்கறி, உணவு, பழக் கழிவுகள், தேயிலைத் தூள், இலைகள். தினமும் ஒப்படைக்கவும்.",
    blueBinTitle = "நீலத் தொட்டி: உலர் / மறுசுழற்சி கழிவு",
    blueBinDesc = "பிளாஸ்டிக், காகிதம், கண்ணாடி, டப்பாக்கள். சுத்தப்படுத்தி வாரத்திற்கு 2 முறை ஒப்படைக்கவும்.",
    redBagTitle = "சிவப்புப் பை: சுகாதார மற்றும் வீட்டு அபாயகர கழிவு",
    redBagDesc = "சானிட்டரி நாப்கின், டயப்பர்கள், மருந்துகள், பேட்டரிகள். செய்தித்தாளில் சுற்றித் தரவும்.",
    goldenRulesTitle = "கழிவுப் பிரித்தல் விதிகள்",

    aiAssistantTitle = "CleanCity AI உதவியாளர்",
    aiAssistantSubtitle = "குப்பை சேகரிப்பு நேரம், கழிவுப் பிரித்தல் விதிகள் அல்லது மாநகராட்சி சேவைகள் குறித்து கேட்கவும்.",
    aiInputPlaceholder = "குப்பை சேகரிப்பு, நேரம், விதிகள் குறித்து கேளுங்கள்...",
    send = "அனுப்பவும்",
    quickQuestionsTitle = "விரைவு கேள்விகள்",
    promptPickupTimes = "இன்று எனது பகுதியில் குப்பை வாகனம் வரும் நேரம் என்ன?",
    promptSegregation = "ஈரக் கழிவு மற்றும் பிளாஸ்டிக்கை எவ்வாறு பிரிக்க வேண்டும்?",
    promptPayFee = "மாதாந்திர பயனர் கட்டணத்தை ஆன்லைனில் எவ்வாறு செலுத்துவது?",
    promptHomeCompost = "வீட்டிலேயே ஈரக் கழிவிலிருந்து இயற்கை உரம் தயாரிப்பது எப்படி?",
    aiThinking = "CleanCity AI பதிலளிக்கிறது...",

    billsTitle = "மாநகராட்சி துப்புரவு பயனர் கட்டணம்",
    billsSubtitle = "திடக்கழிவு விதிகளின்படி மாதாந்திர கட்டாய சேவைக் கட்டணம்.",
    currentOutstanding = "மொத்த நிலுவைத் தொகை",
    payMonthlyServiceFee = "UPI மூலம் கட்டணம் செலுத்தவும்",
    paymentSuccessTitle = "பணம் செலுத்துதல் வெற்றிகரமாக முடிந்தது!",
    upiReference = "UPI குறிப்பு எண்",
    downloadReceipt = "ரசீது பதிவிறக்கம்",
    transactionHistory = "கடந்த கால ரசீதுகள்",
    close = "மூடு"
)

fun getAppStrings(language: String): AppStrings {
    val clean = language.trim()
    return when {
        clean.equals("TE", ignoreCase = true) || clean.contains("Telugu", ignoreCase = true) || clean.contains("తెలుగు") -> TeluguStrings
        clean.equals("HI", ignoreCase = true) || clean.contains("Hindi", ignoreCase = true) || clean.contains("हिन्दी") -> HindiStrings
        clean.equals("KN", ignoreCase = true) || clean.contains("Kannada", ignoreCase = true) || clean.contains("ಕನ್ನಡ") -> KannadaStrings
        clean.equals("TA", ignoreCase = true) || clean.contains("Tamil", ignoreCase = true) || clean.contains("தமிழ்") -> TamilStrings
        else -> EnglishStrings
    }
}

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

@Composable
@ReadOnlyComposable
fun appStrings(): AppStrings = LocalAppStrings.current
